version: '3.9'
services:
  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   container_name: yt-mongodb
  #   networks:
  #     - yt-network
  #   volumes:
  #     - mongoData:/data/db
  #   env_file:
  #     - ./server/.env

  yt-backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 3500:3500
    container_name: yt-node-container
    networks:
      - yt-network
    env_file:
      - ./server/.env
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    # depends_on:
    #   - mongodb

  yt-frontend:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: yt-client-container
    networks:
      - yt-network
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/usr/src/client
    depends_on:
      - yt-backend

networks:
  yt-network:

volumes:
  mongoData: